### PR TITLE
Inventory improvments

### PR DESCRIPTION
**Pull request by aszulc97**
beautiful filtering that took my 10 minutes <3
and very shitty sorting that maybe I'll fix once I'll be less tired 💩
and not so good updating
and toastify

### CODE REVIEW

**Comment by aszulc97** [comment]
and now you can delete items :DD

**Comment by aszulc97** [comment]
yup, change in Tasks broke the trackers, they are not working on master now, but trackers branch fixes it

**Comment by zuzik772** [comment]
btw when u delete an item should I think we should get toaster that says the item was deleted, its usually top right corner and stays there for 4 seconds and then dissapears

**Comment by aszulc97** [comment]
would you like to do it? 😄

**Comment by zuzik772** [comment]
sure how about this
https://www.npmjs.com/package/react-toastify

**Comment by zuzik772** [comment]
> sure how about this https://www.npmjs.com/package/react-toastify

actually flowbite has some, can i make it here or do u want me to merge nad create new branch in case i fuck up? :D

**Review by zuzik772 — APPROVED** [review]
nice work

**Pull request merged**
